name: projekt
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'


dependencies:
  flutter:
    sdk: flutter

  mask_text_input_formatter: ^2.4.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.3
  #firebase
  firebase_auth: ^4.6.3
  cloud_firestore: ^4.8.1
  #service locator
  get_it: ^7.2.0
  #dateFormat
  intl: ^0.18.1
  flutter_icons: ^1.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  firebase_core: ^2.14.0
  dropdown_textfield: ^1.0.8
  get: ^4.6.5
  google_maps: ^6.3.0
  geocoding: ^2.0.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0

flutter:
 

  uses-material-design: true
  assets:
    - assets/images/default.jpg
    - assets/images/football.jpg
    - assets/images/basketball.jpg
    - assets/images/cycling.png
    - assets/images/fitness.jpg
    - assets/images/hockey.jpg
    - assets/images/pool.jpg
    - assets/images/run.jpg
    - assets/images/volleyball.jpg
    - assets/images/yoga.jpg

